#!/bin/bash
cp CMakeLists.txt ../../CMakeLists.txt
cp CMakeLists.txt.user ../../CMakeLists.txt.user.tmp
echo "Start QtCreator and open CMakeLists.txt from NDevils _ROOT_ folder, NOT the one from Make/QtCreator!"
read -rsp "Press any button to exit..." -n1 key
