function net = CNN_xs()
setup;

f=1/100 ;
net.layers = {} ;
net.layers{end+1} = struct('type', 'conv', ...
                           'weights', {{f*randn(3,3,1,3, 'single'), zeros(1, 3, 'single')}}, ...
                           'stride', 2, ...
                           'pad', 0) ;
net.layers{end+1} = struct('type', 'pool', ...
                           'method', 'avg', ...
                           'pool', [2 2], ...
                           'stride', 2, ...
                           'pad', 1) ;
net.layers{end+1} = struct('type', 'relu') ;
net.layers{end+1} = struct('type', 'conv', ...
                           'weights', {{f*randn(2,2,3,2, 'single'), zeros(1,2,'single')}}, ...
                           'stride', 2, ...
                           'pad', 0) ;
net.layers{end+1} = struct('type', 'softmaxloss') ;

net = vl_simplenn_tidy(net) ;

net.trainOpts.batchSize = 100 ;
net.trainOpts.numEpochs = 1000 ;
net.trainOpts.continue = false ;
net.trainOpts.gpus = [] ;
net.trainOpts.learningRate = 0.0002 ;
net.trainOpts.expDir = 'temp' ;
