function net = CNN_big_16()
% Medium net trying with added filters and smaller pooling + added relu and pooling layer.

f=1/100 ;
net.layers = {} ;
net.layers{end+1} = struct('type', 'conv', ...
                           'weights', {{f*randn(5,5,1,8, 'single'), zeros(1, 8, 'single')}}, ...
                           'stride', 2, ...
                           'pad', 2) ;
net.layers{end+1} = struct('type', 'pool', ...
                           'method', 'max', ...
                           'pool', [2 2], ...
                           'stride', 2, ...
                           'pad', 0) ;
net.layers{end+1} = struct('type', 'relu') ;
net.layers{end+1} = struct('type', 'conv', ...
                           'weights', {{f*randn(3,3,8,12, 'single'), zeros(1,12,'single')}}, ...
                           'stride', 1, ...
                           'pad', 1) ;    
net.layers{end+1} = struct('type', 'pool', ...
                           'method', 'max', ...
                           'pool', [2 2], ...
                           'stride', 2, ...
                           'pad', 0) ;                           
net.layers{end+1} = struct('type', 'relu') ;
net.layers{end+1} = struct('type', 'conv', ...
                           'weights', {{f*randn(2,2,12,2, 'single'), zeros(1,2,'single')}}, ...
                           'stride', 1, ...
                           'pad', 0) ;
net.layers{end+1} = struct('type', 'softmaxloss') ;

net = vl_simplenn_tidy(net) ;

net.trainOpts.batchSize = 100 ;
net.trainOpts.numEpochs = 20 ;
net.trainOpts.continue = false ;
net.trainOpts.gpus = [] ;
net.trainOpts.learningRate = 0.001 ;
net.trainOpts.expDir = 'temp' ;
