function net = CNN_medium_16()
% Medium net for 16x16 used on RoboCup

f=1/100 ;
net.layers = {} ;
net.layers{end+1} = struct('type', 'conv', ...
                           'weights', {{f*randn(6,6,1,5, 'single'), zeros(1, 5, 'single')}}, ...
                           'stride', 2, ...
                           'pad', 2) ;
net.layers{end+1} = struct('type', 'pool', ...
                           'method', 'max', ...
                           'pool', [3 3], ...
                           'stride', 3, ...
                           'pad', 1) ;
net.layers{end+1} = struct('type', 'conv', ...
                           'weights', {{f*randn(3,3,5,10, 'single'), zeros(1,10,'single')}}, ...
                           'stride', 2, ...
                           'pad', 1) ;
net.layers{end+1} = struct('type', 'pool', ...
                           'method', 'max', ...
                           'pool', [2 2], ...
                           'stride', 2, ...
                           'pad', 1) ;                       
net.layers{end+1} = struct('type', 'relu') ;
net.layers{end+1} = struct('type', 'conv', ...
                           'weights', {{f*randn(2,2,10,2, 'single'), zeros(1,2,'single')}}, ...
                           'stride', 2, ...
                           'pad', 0) ;
net.layers{end+1} = struct('type', 'softmaxloss') ;

net = vl_simplenn_tidy(net) ;

net.trainOpts.batchSize = 100 ;
net.trainOpts.numEpochs = 10 ;
net.trainOpts.continue = false ;
net.trainOpts.gpus = [] ;
net.trainOpts.learningRate = 0.001 ;
net.trainOpts.expDir = 'temp' ;
